.Dd May 28, 2015
.Dt PLIST2JSON 1
.Sh NAME
.Nm plist2json
.Nd Converts plist input to json
.Sh SYNOPSYS
.Nm plist2json [ files.plist | - ]
.Sh DESCRIPTION
The
.Nm
utility converts plist input to json. The plist input can be read from the
specified file, or directly from stdin.
The resulting json output is then printed to stdout.
.Sh NOTES
The plist format expected is not fully compatible with Apple plists, but rather
it's compatible with the NetBSD's proplib implementation.
.Sh AUTHORS
.An Juan Romero Pardines <xtraeme@voidlinux.eu>
.Sh BUGS
Probably, but I try to make this not happen. Use it under your own
responsability and enjoy your life.
